server:
  port: 8080

spring:
  application:
    name: member-system

  datasource:
    url: jdbc:mysql://localhost:3306/HuiYuanSql?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: xuhu
    password: "422904192"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  swagger-ui:
    path: /swagger-ui.html

yuanqi:
  api-url: https://yuanqi.tencent.com/openapi/v1/agent/chat/completions
  app-id: 2033772830773034880 # 从腾讯元器获取
  app-key: LHYQtxsNKRi7Jw9x0cLZ0GVtm613VR7Y       # 从腾讯元器获取

